name: Deno fmt check

on:
        push:
                branches: [main]
        pull_request:
                branches: [main]

jobs:
        build:
                runs-on: blacksmith-4vcpu-ubuntu-2204
                steps:
                        - uses: actions/checkout@v4
                        - uses: denoland/setup-deno@v2
                          with:
                                  deno-version: v2.x
                        - run: deno fmt --check
